pglib_case = "14_ieee"
export_dir = "data/14_ieee"

floating_point_type = "float64"

[sampler]

[sampler.load]
noise_type = "ScaledUniform"
l          = 0.80               # Lower bound of base load factor
u          = 1.20               # Upper bound of base load factor
sigma      = 0.20               # Relative (multiplicative) noise level.

[OPF]
# OPF formulations to solve for each sample

[OPF.SOCOPF128]
# These settings are meant to solve `SOCWRConic` problems to high precision
type = "SOCOPF"
solver.name = "Clarabel128"
# Tight tolerances
solver.attributes.tol_gap_abs    = 1e-8
solver.attributes.tol_gap_rel    = 1e-8
solver.attributes.tol_feas       = 1e-8
solver.attributes.tol_infeas_rel = 1e-8
solver.attributes.tol_ktratio    = 1e-8
# Reduced accuracy settings
solver.attributes.reduced_tol_gap_abs    = 1e-8
solver.attributes.reduced_tol_gap_rel    = 1e-8
solver.attributes.reduced_tol_feas       = 1e-8
solver.attributes.reduced_tol_infeas_abs = 1e-8
solver.attributes.reduced_tol_infeas_rel = 1e-8
solver.attributes.reduced_tol_ktratio    = 1e-8
